---
- name: Install kubectl
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
  - name: Install cleint tools
    get_url:
      url: "{{ item.link }}"
      dest: "/usr/local/bin/{{ item.cmd }}"
      mode: 0755
    with_items:
    - { link: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64", cmd: "cfssl"}
    - { link: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64", cmd: "cfssljson"}
    - { link: "https://storage.googleapis.com/kubernetes-release/release/v1.10.2/bin/linux/amd64/kubectl", cmd: "kubectl"}
    tags: install
