---
- name: Install app
  become: true
  hosts: all
  tasks:

  - name: Install docker dependencies
    docker_container:
      name: puma-app
      image: fl64/otus-reddit:1.0
      state: started
      ports:
      - "80:9292"
    tags: app
