kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: bqOaN+oq/vLKPNoQLQcGqYhm9kyL8h13IIyLLitGBGA=
      - identity: {}
